
//:--[22551.3874285]
[ '/code', "\\jun.envir.stopSynths" ]
//:--[22551.388699333]
[ '/code', "'jun'.envir play: ( 'vol': [ 1.4814191812018, \"\", 'off' ], 'endframe': 6750651, 'buf': 'birdcarman', 'amp': [ 1.0, \"Xyz(5, 0.2, 0.1, 1.5)\", 'off' ], 
  'startframe': 0, 'playfunc': 'grainfroth', 'trate': [ 0.19784172661871, \"\\\\z5.sr\", 'off' ], 'pos': [ 0.68345323741007, \"\\\\x5.sr\", 'off' ] )" ]
//:--[22569.8872775]
[ '/code', "\\jun.envir.stopSynths" ]